version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.12.1-node
    steps:
      - checkout
      - run: python3 code.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.12.1-node
    steps:
      - checkout
      - run: python3 test_code.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build