version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "cimg/python:3.8.0"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run: python3 assessment_code.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "cimg/python:3.8.0"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run: python3 test_code.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build