version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "cimg/python:3.12.1"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run: python3 assessment_code.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "cimg/python:3.12.1"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            mkdir test-results  # Create a directory for test results
            pytest C:/Users/Boomw/Documents/PWC documents/Year 2 Modules/Professionan_Programming_full_Module/Assessment/Coding_and_test_suite/test_code/--junitxml=test-results/junit.xml  # Update with your test command
      - store_test_results:
          path: test-results
      - store_artifacts:  # Optional: store test result artifacts
          path: test-results
          destination: test-results

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build